package main

const WORLD_CELLDIMENSION = 24
const WORLD_CELLHEIGHT = 24
const WORLD_CELLWIDTH = WORLD_CELLDIMENSION

const WORLD_HEIGHT = 1048
const WORLD_WIDTH = 1048

const WINDOW_HEIGHT = 640
const WINDOW_WIDTH = 640

const WORLD_CELL_PIXEL_HEIGHT = float64(WINDOW_HEIGHT) / float64(WORLD_CELLHEIGHT)
const WORLD_CELL_PIXEL_WIDTH = float64(WINDOW_WIDTH) / float64(WORLD_CELLWIDTH)

const FPS = 60
